import Header from '../components/Header'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html dir='rtl' lang="fa">
      <body className="bg-zinc-900  font-dana">
        <Header />
        {children}
      </body>
    </html >
  )
}
